/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.panels;

import dao.InfoDaoImpl;
import domain.Info;
import firescenne.FireScenneStart;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import util.EnumCardLayer;

/**
 *
 * @author viorel.cojocaru
 */
public class EditPanel extends javax.swing.JPanel {

    /**
     * Creates new form EditPanel
     */
    public EditPanel() {
        initComponents();
    }
    private FireScenneStart jpanelParent;

    public EditPanel(FireScenneStart jpanelParent) {
        initComponents();
        this.jpanelParent = jpanelParent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jComboBoxAnotimpuri = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldTaguri = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescriere = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonAdauga = new javax.swing.JButton();
        jButtonCautare = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jComboBoxAnotimpuri.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "IARNA", "PRIMAVARA", "VARA", "TOAMNA" }));
        jComboBoxAnotimpuri.setToolTipText("Alege anotimpul la care se refera scena");

        jPanel1.setFocusCycleRoot(true);
        jPanel1.setName(""); // NOI18N

        jTextFieldTaguri.setToolTipText("Introduceti cuvinte despartite prin virgula si spatiu");

        jTextAreaDescriere.setColumns(20);
        jTextAreaDescriere.setRows(5);
        jTextAreaDescriere.setToolTipText("Adauga cometarii");
        jScrollPane1.setViewportView(jTextAreaDescriere);

        jLabel2.setText("Cuvinte cheie");

        jLabel3.setText("Comentarii");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addComponent(jTextFieldTaguri))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldTaguri, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)))
                .addContainerGap())
        );

        jButtonAdauga.setText("Adauga");
        jButtonAdauga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdaugaActionPerformed(evt);
            }
        });

        jButtonCautare.setText("Cautare");
        jButtonCautare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCautareActionPerformed(evt);
            }
        });

        jButtonUpdate.setText("Reinnoeste");
        jButtonUpdate.setEnabled(false);
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonUpdate)
                    .addComponent(jButtonAdauga)
                    .addComponent(jButtonCautare))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonAdauga, jButtonCautare, jButtonUpdate});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAdauga)
                .addGap(18, 18, 18)
                .addComponent(jButtonUpdate)
                .addGap(77, 77, 77)
                .addComponent(jButtonCautare)
                .addContainerGap())
        );

        jLabel1.setText("Indica anotimpul");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxAnotimpuri, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxAnotimpuri, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCautareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCautareActionPerformed
        jpanelParent.showCard(EnumCardLayer.SARCHED);
    }//GEN-LAST:event_jButtonCautareActionPerformed

    private void jButtonAdaugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdaugaActionPerformed
        if (jpanelParent.getFileNameStr().length() != 0) {
            infoDao = InfoDaoImpl.getInstance();
            Info info = new Info();
            info.setTags(jTextFieldTaguri.getText());
            info.setTimpIn(jpanelParent.getTimeInStr());
            info.setTimpOut(jpanelParent.getTimeOutStr());
            info.setComments(jTextAreaDescriere.getText());
            info.setFisierNume(jpanelParent.getFileNameStr());
            info.setAnotimp((String) jComboBoxAnotimpuri.getSelectedItem());

            infoDao.saveInfo(info);
            clearFields();

        } else {
            JOptionPane.showMessageDialog(null, "Incarcati fisierul video!");
        }
    }//GEN-LAST:event_jButtonAdaugaActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        if (jpanelParent.getFileNameStr().length() != 0) {
            infoDao = InfoDaoImpl.getInstance();
            Info info = new Info();
            info.setTags(jTextFieldTaguri.getText());
            info.setTimpIn(jpanelParent.getTimeInStr());
            info.setTimpOut(jpanelParent.getTimeOutStr());
            info.setComments(jTextAreaDescriere.getText());
            info.setFisierNume(jpanelParent.getFileNameStr());
            info.setAnotimp((String) jComboBoxAnotimpuri.getSelectedItem());

            infoDao.updateInfo(info);
            clearFields();
            jButtonAdauga.setEnabled(true);
            jButtonUpdate.setEnabled(false);

        } else {
            JOptionPane.showMessageDialog(null, "Incarcati fisierul video!");
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdauga;
    private javax.swing.JButton jButtonCautare;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox jComboBoxAnotimpuri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDescriere;
    private javax.swing.JTextField jTextFieldTaguri;
    // End of variables declaration//GEN-END:variables
    private List<Info> listaInfo = new ArrayList<Info>();
    private InfoDaoImpl infoDao;

    private void clearFields() {
        jTextAreaDescriere.setText("");
        jTextFieldTaguri.setText("");
        jComboBoxAnotimpuri.setSelectedIndex(0);
    }

    public void incarcaDateleInComp(String idStr) {
        infoDao = InfoDaoImpl.getInstance();
        Info info = new Info();

        info = infoDao.findById(idStr);
        String anotimp = info.getAnotimp();
        String time_in = info.getTimpIn();
        String time_out = info.getTimpOut();
        String comments = info.getComments();
        String tags = info.getTags();
        String filepath = info.getFisierNume();
        jButtonUpdate.setEnabled(true);
        jButtonAdauga.setEnabled(false);
        jTextAreaDescriere.setText(comments);
        jTextFieldTaguri.setText(tags);
        jpanelParent.setTime_In(time_in);
        jpanelParent.setTime_Out(time_out);
        jpanelParent.pornesteClipul(filepath, time_in, time_out);
        String[] anotimpuri = {"IARNA", "PRIMAVARA", "VARA", "TOAMNA"};

        for (int i = 0; i < anotimpuri.length; i++) {
            if (anotimpuri[i].equals(anotimp)) {
                jComboBoxAnotimpuri.setSelectedIndex(i);
            }
        }

    }
}
